twig:
    default_path: '%kernel.project_dir%/templates'
    form_theme: 'bootstrap_5_layout.html.twig'
    globals:
        cart: '@App\Service\CartService'

when@test:
    twig:
        strict_variables: true
